services:
  backend:
    build: .
    container_name: promptcraft_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app  # Mount current directory to /app in container for live reload
    ports:
      - "8000:8000"
    env_file:
      - .env # Load environment variables from .env file
    depends_on:
      - database
    # Ensure MONGO_URL uses the service name 'database' when running inside Compose
    # Example .env entry for Compose: MONGO_URL=mongodb://database:27017/promptcraft_db

  database:
    image: mongo:latest
    container_name: promptcraft_mongo_db
    ports:
      - "27017:27017" # Map host port 27017 to container port 27017
    volumes:
      - mongo_data:/data/db # Persist data using a named volume
    # Optional: Add healthcheck for MongoDB
    # healthcheck:
    #   test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 30s

volumes:
  mongo_data:
    # Define the named volume used by the database service 